# Generated by Django 4.1.2 on 2022-11-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="membership",
            field=models.CharField(
                choices=[("B", "Bronze"), ("S", "Silver"), ("G", "Gold")],
                default="Bronze",
                max_length=6,
            ),
        ),
    ]
