# Generated by Django 4.1.2 on 2022-11-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_customer_membership"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Promotions", "verbose_name_plural": "Promotion"},
        ),
    ]
